# Generated by Django 6.0.3 on 2026-03-30 19:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'ciudad',
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{1,5}$', 'Solo letras mayúsculas y números')])),
                ('distancia', models.FloatField()),
                ('ciudadDestino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas_destino', to='rutas.ciudad')),
                ('ciudadOrigen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas_origen', to='rutas.ciudad')),
            ],
            options={
                'db_table': 'ruta',
            },
        ),
    ]
