# Generated by Django 6.0.3 on 2026-03-31 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='ciudadDestino',
            field=models.ForeignKey(db_column='ciudadDestino', on_delete=django.db.models.deletion.PROTECT, related_name='rutas_destino', to='rutas.ciudad'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='ciudadOrigen',
            field=models.ForeignKey(db_column='ciudadOrigen', on_delete=django.db.models.deletion.PROTECT, related_name='rutas_origen', to='rutas.ciudad'),
        ),
    ]
