# Generated by Django 6.0.2 on 2026-04-03 06:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0002_alter_ruta_ciudaddestino_alter_ruta_ciudadorigen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='codigo',
            field=models.CharField(max_length=7, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{1,5}$', 'Solo letras mayúsculas y números')]),
        ),
    ]
