# Generated by Django 6.0.2 on 2026-04-05 19:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0003_alter_ruta_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='codigo',
            field=models.CharField(max_length=7, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z0-9-]{1,7}$', 'Solo letras mayúsculas, números y guiones')]),
        ),
    ]
