# Generated by Django 6.0.2 on 2026-03-26 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPasajero',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20)),
                ('porcentaje_desc', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'tipo_pasajero',
            },
        ),
    ]
