# Generated by Django 6.0.2 on 2026-04-02 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasajeros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellPat', models.CharField(max_length=20)),
                ('apellMat', models.CharField(blank=True, max_length=20, null=True)),
                ('edad', models.IntegerField()),
                ('correoElect', models.EmailField(blank=True, max_length=40, null=True)),
                ('telefono', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'pasajero',
            },
        ),
    ]
