# Generated by Django 6.0.2 on 2026-04-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasajeros', '0002_pasajero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasajero',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
