# Generated by Django 6.0.2 on 2026-04-03 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autobuses', '0002_alter_autobus_estado_alter_autobus_marca_and_more'),
        ('corridas', '0004_corridaasiento'),
        ('pasajeros', '0003_alter_pasajero_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('fechaLimPago', models.DateField()),
                ('cantPasajeros', models.IntegerField()),
                ('subtotal', models.FloatField()),
                ('IVA', models.FloatField()),
                ('total', models.FloatField()),
                ('corrida', models.ForeignKey(db_column='corrida', on_delete=django.db.models.deletion.RESTRICT, related_name='reservaciones', to='corridas.corrida')),
                ('pasajero', models.ForeignKey(db_column='pasajero', on_delete=django.db.models.deletion.RESTRICT, related_name='reservaciones', to='pasajeros.pasajero')),
            ],
            options={
                'db_table': 'reservacion',
            },
        ),
        migrations.CreateModel(
            name='AsientoReservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asiento', models.ForeignKey(db_column='asiento', on_delete=django.db.models.deletion.RESTRICT, related_name='asiento_reservaciones', to='autobuses.asiento')),
                ('reservacion', models.ForeignKey(db_column='reservacion', on_delete=django.db.models.deletion.RESTRICT, related_name='asiento_reservaciones', to='reservaciones.reservacion')),
            ],
            options={
                'db_table': 'asiento_reservacion',
                'unique_together': {('asiento', 'reservacion')},
            },
        ),
    ]
