# Generated by Django 6.0.3 on 2026-03-31 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corridas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EdoCorrida',
        ),
    ]
