# Generated by Django 6.0.3 on 2026-04-01 03:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autobuses', '0002_alter_autobus_estado_alter_autobus_marca_and_more'),
        ('corridas', '0002_delete_edocorrida'),
        ('operadores', '0001_initial'),
        ('rutas', '0002_alter_ruta_ciudaddestino_alter_ruta_ciudadorigen'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdoCorrida',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'Solo letras mayúsculas')])),
                ('descripcion', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[A-Z]{1,10}$', 'Solo letras mayúsculas')])),
            ],
            options={
                'db_table': 'edo_corrida',
            },
        ),
        migrations.CreateModel(
            name='Corrida',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('hora_salida', models.TimeField()),
                ('fecha_salida', models.DateField()),
                ('hora_llegada', models.TimeField()),
                ('fecha_llegada', models.DateField()),
                ('tarifaBase', models.FloatField()),
                ('lugaresDisp', models.IntegerField()),
                ('autobus', models.ForeignKey(db_column='autobus', on_delete=django.db.models.deletion.RESTRICT, related_name='corridas', to='autobuses.autobus')),
                ('operador', models.ForeignKey(db_column='operador', on_delete=django.db.models.deletion.RESTRICT, related_name='corridas', to='operadores.operador')),
                ('ruta', models.ForeignKey(db_column='ruta', on_delete=django.db.models.deletion.RESTRICT, related_name='corridas', to='rutas.ruta')),
                ('estado', models.ForeignKey(db_column='estado', on_delete=django.db.models.deletion.RESTRICT, related_name='corridas', to='corridas.edocorrida')),
            ],
            options={
                'db_table': 'corrida',
            },
        ),
    ]
