# Generated by Django 6.0.2 on 2026-04-03 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autobuses', '0002_alter_autobus_estado_alter_autobus_marca_and_more'),
        ('corridas', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorridaAsiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADO', 'Ocupado'), ('RESERVADO', 'Reservado')], default='DISPONIBLE', max_length=13)),
                ('asiento', models.ForeignKey(db_column='asiento', on_delete=django.db.models.deletion.RESTRICT, related_name='corrida_asientos', to='autobuses.asiento')),
                ('corrida', models.ForeignKey(db_column='corrida', on_delete=django.db.models.deletion.CASCADE, related_name='corrida_asientos', to='corridas.corrida')),
            ],
            options={
                'db_table': 'corrida_asiento',
                'unique_together': {('corrida', 'asiento')},
            },
        ),
    ]
