# Generated by Django 6.0.3 on 2026-03-31 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[A-Za-záéíóúñÁÉÍÓÚÑ]+$', 'Solo se permiten letras')])),
                ('apellPat', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[A-Za-záéíóúñÁÉÍÓÚÑ]+$', 'Solo se permiten letras')])),
                ('apellMat', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^[A-Za-záéíóúñÁÉÍÓÚÑ]+$', 'Solo se permiten letras')])),
                ('fechaNac', models.DateField()),
                ('telefono', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', 'El teléfono debe tener exactamente 10 dígitos')])),
                ('fechaContrato', models.DateField()),
            ],
            options={
                'db_table': 'operador',
            },
        ),
    ]
