# Generated by Django 6.0.2 on 2026-04-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('taquillero', 'Taquillero'), ('pasajero', 'Pasajero')], default='taquillero', max_length=15),
        ),
    ]
