# Generated by Django 6.0.2 on 2026-04-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('taquillero', 'Taquillero'), ('pasajero', 'Pasajero')], default='pasajero', max_length=15),
        ),
    ]
