# Generated by Django 6.0.2 on 2026-03-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EdoCorrida',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'edo_corrida',
            },
        ),
    ]
