# Generated by Django 6.0.2 on 2026-04-03 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autobuses', '0002_alter_autobus_estado_alter_autobus_marca_and_more'),
        ('corridas', '0004_corridaasiento'),
        ('pasajeros', '0003_alter_pasajero_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.FloatField()),
                ('asiento', models.ForeignKey(db_column='asiento', on_delete=django.db.models.deletion.RESTRICT, related_name='boletos', to='autobuses.asiento')),
                ('corrida', models.ForeignKey(db_column='corrida', on_delete=django.db.models.deletion.RESTRICT, related_name='boletos', to='corridas.corrida')),
                ('pasajero', models.ForeignKey(db_column='pasajero', on_delete=django.db.models.deletion.RESTRICT, related_name='boletos', to='pasajeros.pasajero')),
                ('tipoPasajero', models.ForeignKey(db_column='tipoPasajero', on_delete=django.db.models.deletion.RESTRICT, related_name='boletos', to='pasajeros.tipopasajero')),
            ],
            options={
                'db_table': 'boleto',
            },
        ),
    ]
