# Generated by Django 6.0.2 on 2026-03-25 23:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EdoAutobus',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{1,4}$', 'Solo letras mayúsculas y números')])),
                ('descripcion', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'edo_autobus',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('clave', models.CharField(max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{1,5}$', 'Solo letras mayúsculas y números')])),
                ('nombre', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'marca',
            },
        ),
        migrations.CreateModel(
            name='TipoAutobus',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{1,4}$', 'Solo letras mayúsculas y números')])),
                ('descripcion', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tipo_autobus',
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('clave', models.CharField(max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{1,5}$', 'Solo letras mayúsculas y números')])),
                ('nombre', models.CharField(max_length=15)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autobuses.marca')),
            ],
            options={
                'db_table': 'modelo',
            },
        ),
        migrations.CreateModel(
            name='Autobus',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{6}$', 'Debe tener exactamente 6 caracteres alfanuméricos')])),
                ('claveWIFI', models.CharField(blank=True, max_length=20, null=True)),
                ('cantAsientos', models.PositiveIntegerField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autobuses.edoautobus')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autobuses.marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autobuses.modelo')),
                ('tipoAutobus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autobuses.tipoautobus')),
            ],
            options={
                'db_table': 'autobus',
            },
        ),
    ]
