# Generated by Django 6.0.2 on 2026-03-31 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autobuses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autobus',
            name='estado',
            field=models.ForeignKey(db_column='estado', on_delete=django.db.models.deletion.PROTECT, to='autobuses.edoautobus'),
        ),
        migrations.AlterField(
            model_name='autobus',
            name='marca',
            field=models.ForeignKey(db_column='marca', on_delete=django.db.models.deletion.PROTECT, to='autobuses.marca'),
        ),
        migrations.AlterField(
            model_name='autobus',
            name='modelo',
            field=models.ForeignKey(db_column='modelo', on_delete=django.db.models.deletion.PROTECT, to='autobuses.modelo'),
        ),
        migrations.AlterField(
            model_name='autobus',
            name='tipoAutobus',
            field=models.ForeignKey(db_column='tipoAutobus', on_delete=django.db.models.deletion.PROTECT, to='autobuses.tipoautobus'),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='marca',
            field=models.ForeignKey(db_column='marca', on_delete=django.db.models.deletion.PROTECT, to='autobuses.marca'),
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('clave', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('ubicacion', models.CharField(max_length=7)),
                ('autobus', models.ForeignKey(db_column='autobus', on_delete=django.db.models.deletion.CASCADE, to='autobuses.autobus')),
            ],
            options={
                'db_table': 'asiento',
            },
        ),
    ]
